<form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
    <div class="discount">
        <fieldset class="discount-form">
            <label for="coupon_code"><?php echo $this->__('Enter your coupon code if you have one.') ?></label>
            <input type="hidden" name="remove" id="remove-coupone" value="0" />
            <input type="hidden" name="return_url" id="return_url" value="<?php echo $this->getUrl('checkout/onepage') ?>" />
            <div class="input-box">
                <input class="input-text" id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" type="text" />
            </div>
            <div class="buttons-set">
                <?php if (strlen($this->getCouponCode())): ?>
                    <button type="button" title="<?php echo $this->__('Cancel Coupon') ?>" class="grey button" onclick="discountForm.submit(true)" value="<?php echo $this->__('Cancel Coupon') ?>"><span><i class="icon-remove"></i> <?php echo $this->__('Cancel Coupon') ?></span></button>
                <?php else: ?>
                    <button type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="button" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply Coupon') ?>"><span><?php echo $this->__('Apply Coupon') ?></span></button>
                <?php endif;?>
            </div>
        </fieldset>
    </div>
</form>

<script>
    var discountForm = new VarienForm('discount-coupon-form');
    discountForm.submit = function (isRemove) {
        if (isRemove) {
            $('coupon_code').removeClassName('required-entry');
            $('remove-coupone').value = "1";
        } else {
            $('coupon_code').addClassName('required-entry');
            $('remove-coupone').value = "0";
        }
        cart.handleCoupon();
        return false;
    }
</script>
