<div class="cart">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form id="co-shopping-cart" action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
        <table id="shopping-cart-table" class="data-table cart-table">
            <thead>
                <tr>
                    <th>&nbsp;</th> <!-- Product Image -->
                    <th><span class="nobr"><?php echo $this->__('Product Name') ?></span></th>
                    <th></th>  <!-- Edit -->
                    <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span></th>
                    <?php endif ?>
                    <th><span class="nobr"><?php echo $this->__('Unit Price') ?></span></th>
                    <th><?php echo $this->__('Qty') ?></th>
                    <th><?php echo $this->__('Subtotal') ?></th>
                    <th><?php echo $this->__('Remove') ?></th>
                </tr>
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <tr>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    </tr>
                <?php endif; ?>
            </thead>
            <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
            </tbody>
        </table>
        <?php /*
        <table>
            <tbody>
                <tr>
                    <td valign="bottom">
                        <button type="submit"
                            name="update_cart_action"
                            value="update_qty"
                            title="<?php echo $this->__('Update Shopping Cart'); ?>"
                            class="button btn-update"><span><?php echo $this->__('Update Shopping Cart'); ?></span></button>
                        <button type="submit"
                            name="update_cart_action"
                            value="empty_cart"
                            title="<?php echo $this->__('Clear Shopping Cart'); ?>"
                            class="button btn-empty"
                            id="empty_cart_button"><span><?php echo $this->__('Clear Shopping Cart'); ?></span></button>
                            <?php if (!$this->hasError()): ?>
                            <ul class="checkout-types">
                                <?php foreach ($this->getMethods('methods') as $method): ?>
                                    <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                                        <li><?php echo $methodHtml; ?></li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </td>
                    <td class="totals">
                    <?php echo $this->getChildHtml('totals'); ?>
                    </td>
                </tr>
            </tbody>
        </table>
        */ ?>
    </form>
    <?php echo $this->getChildHtml('shopping.cart.table.after'); ?>
</div>
<script>
document.on('dom:loaded', function() {
    cart = new Cart({
        saveUrl: '<?php echo $this->getUrl('checkout/cart/updatePostJson') ?>',
        form:    'co-shopping-cart'
    });
});
</script>