<?php
/**
 * Three different scenarios:
 *
 * 1. Checkout as guest
 * 2. Register
 * 3. Login
 */

$_quote = $this->getQuote();
$_checkoutMethod = $_quote->getCheckoutMethod();
$_isAllowedGuestCheckout = $_quote->isAllowedGuestCheckout();
?>

<?php echo $this->getChildHtml('checkout.onepage.login.extra'); ?>
<?php echo $this->getChildHtml('login_before'); ?>

<h2><?php echo $this->__('Order without account'); ?></h2>

<ul class="form-list">
    <li class="control">
        <button type="button" class="button setCheckoutMethod" value="<?php echo Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER; ?>"><?php echo $this->__('Create account and place order'); ?></button>
    </li>
    <?php if ($_isAllowedGuestCheckout): ?>
    <li class="control">
        <button type="button" class="button setCheckoutMethod" value="<?php echo Mage_Checkout_Model_Type_Onepage::METHOD_GUEST; ?>"><?php echo $this->__('Checkout as Guest'); ?></button>
    </li>
    <?php endif; ?>
</ul>

<h2><?php echo $this->__('Login'); ?></h2>
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
    <fieldset>
        <ul class="form-list">
            <li>
                <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address'); ?></label>
                <div class="input-box">
                    <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
                </div>
            </li>
            <li>
                <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password'); ?></label>
                <div class="input-box">
                    <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                </div>
                <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>"><?php echo $this->__('Forgot your password?'); ?></a>
            </li>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
        </ul>
    </fieldset>
</form>

<div class="buttons-set">
    <p class="required"><?php echo $this->__('* Required Fields'); ?></p>
    <button type="submit" class="button" onclick="onepageLogin(this)"><?php echo $this->__('Log in and place order'); ?></button>
</div>
