<h2><?php echo $this->__('Payment Method'); ?></h2>
<script>
    var quoteBaseGrandTotal = <?php echo (float)$this->getQuoteBaseGrandTotal(); ?>;
    var checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
    var lastPrice;

    document.observe('dom:loaded', function() {
        payment = new PaymentMethod('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
        payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
    });
</script>
<form action="" id="co-payment-form">
    <fieldset>
        <?php echo $this->getChildHtml('methods') ?>
    </fieldset>
</form>
