<?php if ($this->isVisible()): ?>
    <h2><?php echo $this->__('Shipping Method'); ?></h2>

    <form id="co-shipping-method-form" action="">
        <div id="checkout-shipping-method-load">
            <?php echo $this->getChildHtml('available') ?>
        </div>
        <div id="onepage-checkout-shipping-method-additional-load">
            <?php echo $this->getChildHtml('additional') ?>
        </div>
    </form>
    <script>
        document.observe('dom:loaded', function() {
            shippingMethod = new ShippingMethod(
                {
                    form: 'co-shipping-method-form',
                    saveUrl: "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>",
                    relations: ['review', 'cart']
                }
            );
        });
        if ($('co-shipping-method-form').select('input').length == 1) {
            shippingMethod.save()
        }
    </script>
<?php endif; ?>